-- require("core.plugin_config.ui.bufferline")
-- require("core.plugin_config.ui.staline")
-- require("core.plugin_config.ui.dashboard")
require("core.plugin_config.ui.devicon")
require("core.plugin_config.ui.lualine")
require("core.plugin_config.ui.noice")
